### ISSUE TITLE
Varianta "Použitá" by neměla mít červenou barvu

### ISSUE THREAD

**Issue by milanskaut** [skaut/srs-vstupenky#22]
Po naskenování kódu se zobrazí buďto zelený nápis "Platná" nebo červené nápisy "Neplatná" či "Použitá".

Zatímco Neplatná je v pořádku a měla by být výrazná a červená, tak "Použitá" je v pro kontrolory přijatá hodnota a byla by vhodnější oranžová barva. 

![image](https://github.com/skaut/srs-vstupenky/assets/131680899/2372358f-aa4d-4f5c-8e65-bb4c77fdfac3)

**Comment by jan-stanek** [comment]
Upraveno
