### ISSUE TITLE
Fotografie je ořízlá (na menších displejích)

### ISSUE THREAD

**Issue by milanskaut** [skaut/srs-vstupenky#23]
Na testovaném telefonu je ve velkém množství případů fotografie ořízlá a navíc malá.

![image](https://github.com/skaut/srs-vstupenky/assets/131680899/523f968f-48b7-4daa-9ec8-df82dfcfd067) ![image](https://github.com/skaut/srs-vstupenky/assets/131680899/c6e99eed-efa6-4d16-b3bc-2a44f42addda)

Jelikož fotografie je vyžadována pro vstupenku a je pro nás důležitější jak jméno, zasloužila by si **vlastní řádek a větší prostor**.

**Comment by milanskaut** [comment]
Podobný problém nastává u přehledu datumů a časů kontrol, kdy by se nemusel zobrazit čas, který by mohl být rozhodující pro kontrolujícího:

![image](https://github.com/skaut/srs-vstupenky/assets/131680899/b6cd7856-c3f8-4422-85b0-5a873fe96632)

**Comment by jan-stanek** [comment]
Fotku jsem přesunu, aby měla větší prostor. Zobrazení na menších displejích budu řešit v #26
